### ISSUE TITLE
win32 specific Win32::IPC dependency missing

### ISSUE THREAD

**Issue by rurban** [ingydotnet/inline-c-pm#40] opened 2015-06-07 22:14 UTC
With EUMM it would be trivial to add the required MSWin32 dependency Win32::IPC,
but I have no idea how to add it your build system. Is there only Meta, or is there more?

It fails to build on windows smokers which do not have Win32::IPC installed.
e.g. http://www.cpantesters.org/cpan/report/d3d8beb6-6dbd-1014-9f5e-99bfe3f2b8ca

**Comment by wbraswell** [comment] 2019-01-22 18:43
@sisyphus 
How can we properly add Win32::IPC as a dependency of Inline::C?
If you just tell me what to do, then I will create a pull request etc.

**Comment by sisyphus** [comment] 2019-01-23 00:53
I don't know.
Does anyone know what the problem actually is?

First thing I do whenever I've just built a new perl on Windows (eg 4
configurations of 5.29.7, as I did yesterday) is to run 'cpan -fi
Inline::C'.
And that always works fine for me.

I use force because there's a couple of Inline::C tests that fail near the
end. Those failures don't bother me, and no-one else experiences them, so
I'm quite content to leave them alone and keep using force.

So ... my first thought was Win32::IPC might require force, but that's not
the case. I've just manually removed if from a couple of the 5.29.7 builds
that I created yesterday and then successfully ran 'cpan -i Win32::IPC'.

Does anyone know the reason that Win32::IPC is not being installed on these
Windows smokers when Inlline::C is built ?

Is it a deficiency in Inline::C ? ... or a deficiency in the smoking
environment ?

Cheers,
Rob

**Comment by wbraswell** [comment] 2019-01-23 02:59
Of the 20 failing Win32 tests for Inline::C v0.78, 19 of them are due to the missing Win32::Mutex error:
http://www.cpantesters.org/cpan/report/24fc8586-6bf9-1014-9fd4-c2aa8038f308
http://www.cpantesters.org/cpan/report/01033ab2-6bf6-1014-bc48-f1ee15f2f6ad
http://www.cpantesters.org/cpan/report/fae85659-6ccc-1014-ac47-5aac8038f308
http://www.cpantesters.org/cpan/report/06e666c7-6c52-1014-86c5-018b64ad720a
http://www.cpantesters.org/cpan/report/4e99b992-6d28-1014-85e9-b6b18038f308
http://www.cpantesters.org/cpan/report/3e435fc6-6c15-1014-b528-4657074be7a3
http://www.cpantesters.org/cpan/report/810d4307-6c70-1014-8575-838b271e9b05
http://www.cpantesters.org/cpan/report/1c2c0958-3212-11e8-9cbd-bb4c3e020320
http://www.cpantesters.org/cpan/report/cfc48e66-6c02-1014-a52f-72a58038f308
http://www.cpantesters.org/cpan/report/c54a39a2-bbe5-1014-9183-40e25f496936
http://www.cpantesters.org/cpan/report/1aea1bd9-6c0d-1014-be32-12aa8038f308
http://www.cpantesters.org/cpan/report/e64fe32f-6bfa-1014-bdbe-c0fdc3113a6d
http://www.cpantesters.org/cpan/report/3e06b1b4-6c00-1014-b301-7e76bb4651c1
http://www.cpantesters.org/cpan/report/86ff5c91-6c87-1014-b695-2028cfb58d10
http://www.cpantesters.org/cpan/report/eeed342e-6cad-1014-9744-7aa68038f308
http://www.cpantesters.org/cpan/report/c0e2aa0a-6cd6-1014-a88b-3ee2d5a096b1
http://www.cpantesters.org/cpan/report/52d0a274-6bf5-1014-9acf-88d089f6a4c1
http://www.cpantesters.org/cpan/report/6b044406-6c52-1014-aa86-470c99043735
http://www.cpantesters.org/cpan/report/ff0ea72c-6bf9-1014-9005-4cf2c5b556df

Only 1 of the failing Win32 tests is due to something other than missing Win32::Mutex; it appears to have an old incompatible version of Inline installed which is not related to this issue:
http://www.cpantesters.org/cpan/report/cbf280e9-6bf9-1014-bc51-f8d3665dec09

For Inline::C v0.78, there are 57 total Win32 tests, of which 37 are passing and (as mentioned) 20 are failing.  We have 19/57 which is a 33% failure rate due only to missing Win32::Mutex.  This seems to indicate that is is a relatively common occurrence that Win32::Mutex is NOT installed in Windows Perl by default, so we SHOULD be explicitly adding it to the Inline::C dependencies.

@sisyphus 
Is my reasoning valid here?

**Comment by sisyphus** [comment] 2019-01-23 04:52
Your reasoning is quite valid.
However, I think we've already explicitly added Win32::Mutex to the
Inline::C dependencies for Windows via this entry in the Makefile.PL:

if ( $^O eq 'MSWin32' ) {
 $WriteMakefileArgs{PREREQ_PM}{'Win32::Mutex'} = '1.09';
}

And that's working fine for me. Every time I install Inline::C on a fresh
build of perl it installs Win32::Mutex along with a heap of other
dependencies.

How come its working fine for me, but not for smokers ?
Is it because the smokers additionally require an entry for Win32::Mutex
somewhere in one of the "META" files, as I think Reini might have
been suggesting ?

Cheers,
Rob

**Comment by rurban** [comment] 2019-01-23 14:13
This is a normal EUMM project, hence the deps need to be specified as in
every other EUMM project. The PREREQ_PM array and optionally for the YAML
and JSON generation the META entries. See perldoc ExtUtils::MakeMaker.
Check if meta generation is broken by looking at the YAML and JSON files in
the tarball.

Am Mi., 23. Jan. 2019, 06:25 hat William N. Braswell, Jr. <
notifications@github.com> geschrieben:

**Comment by rurban** [comment] 2019-01-23 21:34
Exactly. I will look into that later, I'm away.

**Comment by perlpunk** [comment] 2019-01-24 17:59
It looks to me like the META.yaml/META.json files are correct.

Win32::Mutex is only needed on Win32, but AFAIK CPAN::Meta currently has no way to express such dynamic dependencies. We can't put it into the static META files because we don't want this on other operating systems.

The only thing you can specify in META is `dynamic_config: 1`:
> "A boolean flag indicating whether a Build.PL or Makefile.PL (or similar) must be executed to determine prerequisites."
https://metacpan.org/pod/CPAN::Meta::Spec#dynamic_config

And the Makefile.PL has the dependency.

Both META.yaml/META.json have `dynamic_config: 1`, so I wonder why smokers don't adhere to that.
https://metacpan.org/source/TINITA/Inline-C-0.78/META.json#L6
https://metacpan.org/source/TINITA/Inline-C-0.78/META.yml#L16

**Comment by perlpunk** [comment] 2019-01-24 18:43
So PERL5LIB correctly contains Win32-IPC. But as we can see from the error message the directories reported in PERL5LIB get lost:
```
Can't locate Win32/Mutex.pm in @INC
 (@INC contains: C:\strawberry\cpan\build\Inline-0.80-0/blib/lib/
 C:\strawberry\cpan\build\Inline-C-0.79_001-0\blib\lib
 C:\strawberry\cpan\build\Inline-C-0.79_001-0\blib\arch
 C:\strawberry\cpan\build\Inline-0.80-0/blib/arch
 C:\strawberry\cpan\build\Inline-0.80-0/blib/lib
 C:/strawberry/perl/site/lib
 C:/strawberry/perl/site/lib
 C:/strawberry/perl/vendor/lib
 C:/strawberry/perl/lib .) at C:/strawberry/perl/lib/if.pm line 13.
```
So why does PERL5LIB get lost? I suspect this happens here:
https://metacpan.org/source/TINITA/Inline-C-0.78/lib/Inline/C.pm#L880
as this is the only place where perl calls itself.

**Comment by wbraswell** [comment] 2019-01-24 18:46
@perlpunk 
Wow great sleuthing!  I don't have any way to test this myself, but perhaps @sisyphus or @rurban do?

**Comment by wbraswell** [comment] 2019-01-25 02:30
@bulk88 
Any thoughts on why PERL5LIB is getting lost here???

**Comment by sisyphus** [comment] 2019-01-25 05:44
PERL5LIB gets clobbered in Inline.pm's create_config_file() at line 810:

    local $ENV{PERL5LIB} if defined $ENV{PERL5LIB};

At least, if I comment out that line, everything goes ok and the test suite
passes - except for t/27inline_maker.t, which always fail for me,
irrespective.

Might we safely replace that line with:

unless($^O =~ /MSWin32/I) {
    local $ENV{PERL5LIB} if defined $ENV{PERL5LIB};
}

What might such a change break ?
Who understands the point of localizing PERL5LIB ?

I notice that PERL5OPT is also localized. Might that bight us at some stage
?

Cheers,
Rob

**Comment by perlpunk** [comment] 2019-01-25 08:48
@sisyphus interesting.
Maybe this code is somehow broken?
https://metacpan.org/source/INGY/Inline-0.80/lib/Inline.pm#L822
```
my @_inc = map { "-I$_" }
($inline,
 grep {(-d File::Spec->catdir($_,"Inline") or
 -d File::Spec->catdir($_,"auto","Inline") or 
 -e File::Spec->catdir($_,"Parse/RecDescent.pm"))} @INC);
system $perl, @_inc, "-MInline=_CONFIG_", "-e1", "$dir"
...
```

As far as I can see this should actually replace the need for using PERL5LIB, but maybe Mutex.pm ends up somewhere else?
Does it work if you add "Win32/Mutex.pm" to that grep?

**Comment by sisyphus** [comment] 2019-01-25 11:02
Aaah, yes ... adding
or -e File::Spec->catdir($_,"Win32/Mutex.pm")
to the grep conditions has the desired effect .... and also feels like the
right thing to do ;-)

Pushed to git in commit 3b4ea7b92fdf23035000e09e829f22cc934b55c0

Seems a bit odd to be taking care of Inline::C issues inside the Inline
module, but the relationship has always been a bit like that (for some
definition of "bit like that").
Please feel free to revert/modify if what I've done is incorrect.

Nice work, Tina.
Kudos to Will for making things happen.

Cheers,
Rob.

**Comment by mohawk2** [comment] 2019-01-25 12:52
I expect `Inline` doesn't rely on `PERL5LIB` in case the build stage gets run later, with different environment. However, there is no earthly reason why it's doing the `grep` it's doing: it should capture the whole of `@INC`. @sisyphus, disagree?

**Comment by wbraswell** [comment] 2019-01-25 17:16
@sisyphus @perlpunk 
great job with this fix!

Out of curiosity, why do we have the strategy of making case-by-case exceptions such as "Parse/RecDescent.pm" or "Win32/Mutex.pm", instead of just NOT clobbering PERL5LIB in the first place?

**Comment by sisyphus** [comment] 2019-01-26 01:40
Do you mean that we could simply populate @_inc with:

my @_inc = map { "-I$_" } @INC;

That seems to be working fine for me, both inside and outside of
Test::Harness. (At least it's fine with Inline::C - I haven't yet tried
building Inline itself with that change.)

It assumes that everything that needs to be in @INC is already there - and
that seems to be the case.
I suspect the original grepping was done because there were some
directories that were not in @INC, but needed to be included. (That now
seems to NOT be the case. Is perl doing something differently now or was it
always like that ?)

I'll test it over a range of perl versions (windows only) and get back.

Cheers,
Rob

**Comment by wbraswell** [comment] 2019-01-26 02:18
@sisyphus 
Yes I believe that is approximately what I am saying, although I do not know if this is actually correct or not...

**Comment by sisyphus** [comment] 2019-01-26 05:53
That post of mine was written in response to mohawk2's. Looks like I
managed to get it stuck in the wrong place in the queue ;-)

Anyway, the simplified method of assigning to @_inc with:

my @_inc = map { "-I$_" } @INC;

hasn't broken any Inline-80 or Inline-C-0.79_001 tests for me - tested on
Windows for perls  5.10.0 through to 5.28.0.

So I don't mind if someone wants to commit that to git, or just leave us go
down the path of adding Win32::Mutex to the grep list.

It would be nice to get rid of the localizing of PERL5LIB and that probably
wouldn't break any tests either. But I can't help feeling that there's a
valid case for localizing PERL5LIB under some usage case, even though I
can't properly grasp just how that plays out.

So ... we need to get a new version of Inline released before we can get
the Win32 smokers to start testing Inline::C.

Cheers,
Rob

**Comment by wbraswell** [comment] 2019-01-26 06:34
@sisyphus 
Okay sorry I got confused with the mixed up messages.  :-P
I vote for releasing the ```File::Spec->catdir($_,"Win32/Mutex.pm")``` code now on CPAN to see if it solves all the Win32 failures w/out causing any other unexpected failures.
If all goes well, we could then try another CPAN testers release with the experimental generic ```my @_inc = map { "-I$_" } @inc;``` code, which could in theory cause unforeseen issues because we are disabling all the ```grep``` behavior w/out really understanding why.
(Either way, we are already due for another CPAN dev release to test the latest fix for the still-pending include dir issue https://github.com/ingydotnet/inline-c-pm/issues/72)

**Comment by perlpunk** [comment] 2019-01-26 10:53
Yes, this was also my question. Why don't we keep @INC completely and perform a grep?
But just releasing the Win32::Mutex fix would help us now going forward with Inline::C, I agree.

@ingydotnet do you want me to do a release of Inline? Or who should & can do one? I would need a commit bit and CPAN comaint.
I see there have been two dev releases in 2018 without a following regular release.
We need a regular release so that smokers of Inline::C install it. Any reasons not to do one?

**Comment by perlpunk** [comment] 2019-01-26 12:08
I just released 0.79_002. I guess it will take some more time until we can get an Inline.pm release out.

**Comment by wbraswell** [comment] 2019-01-26 18:37
@sisyphus Do you still have a CPAN commit bit for Inline?  If so, can you please make a CPAN dev release of Inline v0.80_03 w/ your latest commit https://github.com/ingydotnet/inline-pm/commit/3b4ea7b92fdf23035000e09e829f22cc934b55c0 ?

**Comment by wbraswell** [comment] 2019-02-19 04:57
Inline v0.81 has been released, which includes this commit:
https://github.com/ingydotnet/inline-pm/commit/3b4ea7b92fdf23035000e09e829f22cc934b55c0

@sisyphus says "Inline-0.81 looking fine here - and enabling Win32::Mutex to be found via PER5LIB on Windows."
https://github.com/ingydotnet/inline-c-pm/issues/72#issuecomment-460187963

Does this mean we can close this issue as being correctly resolved?  How do we know for sure if the issue is actually solved?

**Comment by sisyphus** [comment] 2019-02-27 03:22
The only indication that it's solved will be the absence of the error.
However, the fix is tested only when someone relies on PERL5LIB to locate
Win32::Mutex - and I'm certainly not interested in creating a test script
that emulates
 those conditions.

I did wonder whether similar problems might arise if the Pegex modules were
being located via PERL5LIB, but my testing on Windows 10 indicates there's
no such problem.

Probably should wait 'til at least the next stable release of Inline::C has
been tested by the affected smoker(s) before closing.

Cheers,
Rob

**Comment by wbraswell** [comment] 2019-03-06 04:14
@sisyphus 
Okay sounds like a good plan!  :-)

**Comment by mohawk2** [comment] 2019-04-02 18:29
Can this be closed?

**Comment by wbraswell** [comment] 2019-04-02 18:56
I think the plan is to keep this issue open until Inline::C 0.79 is fully released on CPAN and we have waited a sufficient period of time for CPAN testers to report errors.

**Comment by perlpunk** [comment] 2019-04-27 09:15
Ok, so I think it can be closed :)

**Closed by perlpunk** 2019-04-27 09:15 UTC

**Comment by wbraswell** [comment] 2019-05-06 19:32
Yes I agree this issue can be closed for now, so far all Win32 tests are passing for Inline 0.80:
http://matrix.cpantesters.org/?dist=Inline-C%200.80;os=mswin32;reports=1
